# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: WeepingOphelia
email: workman.calvin@gmail.com
description: A portfolio of coding projects, writing and digital artwork by Calvin Workman
baseurl: "/folio" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: WeepingOphelia
github_username:  WeepingOphelia

# Build settings
theme: minima
plugins:
  - jekyll-feed
minima:
  date_format: "%d %B %Y; %H.%M"
show_excerpts: true

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
